//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cm_container_desc
    {
        public int container_desc_gkey { get; set; }
        public int container_desc_height { get; set; }
        public int container_desc_length { get; set; }
        public string container_desc_type { get; set; }
        public int container_desc_latest_editor { get; set; }
        public System.DateTime container_desc_updated_time { get; set; }
        public Nullable<int> container_desc_recore_status { get; set; }
    }
}
