//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_contract
    {
        public int contract_gkey { get; set; }
        public string contract_name { get; set; }
        public int contract_customer_id { get; set; }
        public string contract_route { get; set; }
        public System.DateTime contract_start_date { get; set; }
        public System.DateTime contract_end_date { get; set; }
        public string contract_desc_chn { get; set; }
        public string contract_desc_eng { get; set; }
        public string contract_currency { get; set; }
        public int contract_creator { get; set; }
        public int contract_latest_editor { get; set; }
        public System.DateTime contract_creation_time { get; set; }
        public System.DateTime contract_updated_time { get; set; }
        public Nullable<int> contract_record_status { get; set; }
    }
}
