//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_customer
    {
        public int customer_id { get; set; }
        public string customer_name_chn { get; set; }
        public string customer_name_eng { get; set; }
        public string customer_addr { get; set; }
        public string customer_contact_person { get; set; }
        public string customer_phone_num { get; set; }
        public int customer_creator { get; set; }
        public System.DateTime customer_creation_time { get; set; }
        public int customer_latest_editor { get; set; }
        public System.DateTime customer_updated_time { get; set; }
        public Nullable<int> customer_record_status { get; set; }
    }
}
