//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HarbourChargingEntities : DbContext
    {
        public HarbourChargingEntities()
            : base("name=HarbourChargingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cm_container_desc> cm_container_desc { get; set; }
        public virtual DbSet<cr_tariff> cr_tariff { get; set; }
        public virtual DbSet<ct_charge_subject> ct_charge_subject { get; set; }
        public virtual DbSet<ct_contract> ct_contract { get; set; }
        public virtual DbSet<ct_customer> ct_customer { get; set; }
        public virtual DbSet<invoice_berthage> invoice_berthage { get; set; }
        public virtual DbSet<invoice_container_list> invoice_container_list { get; set; }
        public virtual DbSet<invoice_detail> invoice_detail { get; set; }
        public virtual DbSet<invoice_head> invoice_head { get; set; }
        public virtual DbSet<pl_func_parameters> pl_func_parameters { get; set; }
        public virtual DbSet<pl_function_priviledge> pl_function_priviledge { get; set; }
        public virtual DbSet<pl_menu> pl_menu { get; set; }
        public virtual DbSet<pl_role> pl_role { get; set; }
        public virtual DbSet<pl_user_info> pl_user_info { get; set; }
        public virtual DbSet<pl_user_role_info> pl_user_role_info { get; set; }
        public virtual DbSet<tr_truckinfo> tr_truckinfo { get; set; }
        public virtual DbSet<tr_trucktimes> tr_trucktimes { get; set; }
        public virtual DbSet<vs_berthplan> vs_berthplan { get; set; }
        public virtual DbSet<vs_vesselinfo> vs_vesselinfo { get; set; }
    }
}
