//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_berthage
    {
        public int invoice_gkey { get; set; }
        public string invoice_charge_subject_code { get; set; }
        public int invoice_voyage_id { get; set; }
        public string invoice_voyage_in_seq { get; set; }
        public string invoice_voyage_out_seq { get; set; }
        public string invoice_voyage_route { get; set; }
        public System.DateTime invoice_voyage_pull_start_date { get; set; }
        public System.DateTime invoice_voyage_pull_end_date { get; set; }
    }
}
