//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_container_list
    {
        public int invoice_gkey { get; set; }
        public int invoice_charge_subject_code { get; set; }
        public int invoice_container_gkey { get; set; }
        public int invoice_container_no { get; set; }
        public int invoice_container_length { get; set; }
        public int invoice_container_height { get; set; }
        public string invoice_container_type { get; set; }
    }
}
