//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_detail
    {
        public int invoice_gkey { get; set; }
        public string invoice_charge_subject_code { get; set; }
        public string invoice_charge_desc_chn { get; set; }
        public string invoice_charge_desc_eng { get; set; }
        public int invoice_tariff_amount { get; set; }
        public int invoice_count { get; set; }
        public int invoice_tariff_total_amount { get; set; }
    }
}
