//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_function_priviledge
    {
        public int func_priv_key { get; set; }
        public int func_priv_role_id { get; set; }
        public int func_priv_function_para_key { get; set; }
        public int func_priv_function_enable { get; set; }
        public Nullable<int> func_priv_control_enable { get; set; }
        public Nullable<int> func_priv_control_visable { get; set; }
        public Nullable<int> func_priv_record_status { get; set; }
        public System.DateTime func_priv_creation_time { get; set; }
        public int func_priv_creator { get; set; }
        public int func_priv_latest_editor { get; set; }
        public System.DateTime func_priv_updated_time { get; set; }
    
        public virtual pl_role pl_role { get; set; }
        public virtual pl_func_parameters pl_func_parameters { get; set; }
    }
}
