//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_role
    {
        public int role_id { get; set; }
        public string role_name { get; set; }
        public int role_creator { get; set; }
        public System.DateTime role_creation_time { get; set; }
        public int role_latest_editor { get; set; }
        public System.DateTime role_updated_time { get; set; }
        public Nullable<int> role_record_status { get; set; }
    }
}
