//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_user_role_info
    {
        public int user_role_gkey { get; set; }
        public int user_role_role_id { get; set; }
        public int user_role_user_id { get; set; }
        public int user_role_creator { get; set; }
        public System.DateTime user_role_creation_time { get; set; }
        public int user_role_latest_editor { get; set; }
        public System.DateTime user_role_updeted_time { get; set; }
        public Nullable<int> user_role_record_status { get; set; }
    
        public virtual pl_role pl_role { get; set; }
        public virtual pl_user_info pl_user_info { get; set; }
    }
}
