//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_truckinfo
    {
        public int truck_no { get; set; }
        public int truck_customer_id { get; set; }
        public int truck_creator { get; set; }
        public System.DateTime truck_creation_time { get; set; }
        public int truck_latest_editor { get; set; }
        public System.DateTime truck_latest_updated_time { get; set; }
        public Nullable<int> truck_record_status { get; set; }
    }
}
