//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_trucktimes
    {
        public int trucktimes_gkey { get; set; }
        public System.DateTime trucktimes_in_time { get; set; }
        public System.DateTime trucktimes_out_time { get; set; }
        public int trucktimes_truck_no { get; set; }
        public int trucktimes_creator { get; set; }
        public System.DateTime trucktimes_creation_time { get; set; }
        public int trucktimes_latest_editor { get; set; }
        public System.DateTime trucktimes_latest_updated_time { get; set; }
        public Nullable<int> trucktimes_record_status { get; set; }
    }
}
