//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vs_berthplan
    {
        public int berthplan_gkey { get; set; }
        public int berthplan_vessel_gkey { get; set; }
        public string berthplan_in_seq { get; set; }
        public string berthplan_out_seq { get; set; }
        public int berthplan_route { get; set; }
        public int berthplan_creator { get; set; }
        public System.DateTime berthplan_creation_date { get; set; }
        public int berthplan_latest_editor { get; set; }
        public System.DateTime berthplan_latest_updated_time { get; set; }
        public Nullable<int> berthplan_record_status { get; set; }
    }
}
