//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vs_vesselinfo
    {
        public int vessel_id { get; set; }
        public int vessel_length { get; set; }
        public int vessel_tonage { get; set; }
        public int vessel_creator { get; set; }
        public System.DateTime vessel_creation_time { get; set; }
        public int vessel_latest_editor { get; set; }
        public System.DateTime vessel_updeted_time { get; set; }
        public int vessel_customer_id { get; set; }
    }
}
